services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PUBLIC_URL=${PUBLIC_URL:-http://localhost:8000}
    volumes:
      - api_files:/app/files
    networks:
      - youtube-dl-bot

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    environment:
      - TOKEN=${TOKEN}
      - API_URL=${API_URL:-http://api:8000}
    volumes:
      - bot_temp:/app/temp
    depends_on:
      - api
    networks:
      - youtube-dl-bot

volumes:
  api_files:
    driver: local
  bot_temp:
    driver: local

networks:
  youtube-dl-bot:
    driver: bridge
